# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-symlinks
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: fix-encoding-pragma
        args: [--pragma, '# coding: utf-8']
default_language_version:
    python: python3
fail_fast: false
