# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-symlinks
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        # mypy runs from an isolated venv, without the project dependencies.
        # specific stuff can be added with:
        #additional_dependencies: [tokenize-rt==3.2.0]
        args: [--no-namespace-packages]
default_language_version:
    python: python3
fail_fast: false