#!/usr/bin/env python
# coding: utf-8

def prepend_src_dir():
    """Prepends src dir to the path if executed from the git repo without installing."""
    try:
        from pathlib import Path
    except ImportError:
        from pathlib2 import Path
    pwd = Path(__file__).parent

    src_dir = pwd / 'src'
    if src_dir.is_dir:
        import sys
        sys.path.insert(0, str(src_dir))


if __name__ == "__main__":
    prepend_src_dir()

    from gqlspection import cli
    cli()
