name: Post a comment to PR with a coverage report

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  coverage:
    name: "Post a comment with a coverage report"
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install 'runme'
        uses: ./.github/actions/install-runme
        with:
          version: 0.3.0

      - name: Install dependencies
        run: runme deps

      - name: Calculate coverage
        run: runme coverage.calculate

      - name: Post coverage report
        run: |
          # Check if there are previous comments by github-actions bot in the pull request
          if gh pr view ${{ github.event.number }} --json comments -q '.[][].author.login == "github-actions"' | grep -q true; then
            echo "Modify existing comment"
            runme coverage.github_action | gh pr comment ${{ github.event.number }} --edit-last --body-file -
          else 
            echo "Create a new comment"
            runme coverage.github_action | gh pr comment ${{ github.event.number }} --body-file -
          fi
        env:
          GH_TOKEN: ${{ github.token }}
